apiVersion: apps/v1
kind: Deployment
metadata:
  name: gonyast
spec:
  selector:
    matchLabels:
      app: gonyast
  template:
    metadata:
      labels:
        app: gonyast
    spec:
      containers:
      - name: gonyast
        image: gonyast:local
        resources:
          requests:
            memory: "32Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8000